version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d-%H:%M:%S"
handlers:
  file_handler:
    class: logging.FileHandler
    filename: logs/ml_project.log
    level: DEBUG
    formatter: simple
  file_warning_handler:
    class: logging.FileHandler
    filename: logs/ml_project.warn
    level: WARNING
    formatter: simple
loggers:
  ml_project:
    level: DEBUG
    handlers: [file_handler]
  ml_project_warning:
    level: WARNING
    handlers: [file_warning_handler]