input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
pretrained_model_path: "models/model.pkl"
predictions_path: "data/predicted/predictions.csv"
splitting_params:
  val_size: 0.2
  random_state: 1234
train_params:
  model_type: "DecisionTreeClassifier"
  random_state: 1234
feature_params:
  use_log_trick: False
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - "fbs"
  target_col: "target"